#!/bin/bash
NUMBER1=100
NUMBER2=23
RESULT=$((NUMBER1+NUMBER2))
echo ${RESULT}

NUMBER1=something
NUMBER2=anything
RESULT=$((NUMBER1+NUMBER2))
echo ${RESULT}

NUMBER1=$1
NUMBER2=$2
RESULT=$((NUMBER1+NUMBER2))
echo ${RESULT}